export const CREATE_POST = 'CREATE_POST' 
export const UPDATE_POST = 'UPDATE_POST' 
export const DELETE_POST = 'DELETE_POST' 
export const LIKE_POST  = 'LIKE_POST'  
export const FETCH_POSTS_BY_PAGE  = 'FETCH_POSTS_BY_PAGE'   
export const FETCH_POSTS_BY_SEARCH  = 'FETCH_POSTS_BY_SEARCH'  
export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'
export const SIGNUP = 'SIGNUP'
export const SIGNIN = 'SIGNIN'

